import { RiceBugProjectImp } from '../model/RiceBugProject';
import { RiceBugTaskImp } from '../model/RiceBugTask';
import { Worker } from './../enum/worker.enum';

export const taskConfig = [
  // 第一回合
  new RiceBugProjectImp(1, '米ber Login', true,
  { current: 3, last: 1 },
  { current: 5000, last: 5000 },
  [
    new RiceBugTaskImp('1-1', '確認登入系統的規格文件', Worker.RO, 4),
    new RiceBugTaskImp('1-2', '審核相關成本', Worker.CFO, 4),
    new RiceBugTaskImp('1-3', '製作系統的login功能請找LE協助建置資料庫環境', Worker.RD, 4),
    new RiceBugTaskImp('1-4', '製作系統的login功能', Worker.CM, 4),
    new RiceBugTaskImp('1-5', '協助TO架設伺服器，並建置Proxy 協助IT Support建置資料庫', Worker.LE, 5),
    new RiceBugTaskImp('1-6', '建置資料庫, Config V1', Worker.ITSUPORT, 5),
    new RiceBugTaskImp('1-7', '架設米ber伺服器V1', Worker.TO, 5),
  ],
  {
    config: 1,
    server: 1,
    proxy: 1
  }),
  new RiceBugProjectImp(1, '蝦米購物 login error', false,
  { current: -3, last: -3 },
  { current: -1000, last: -1000 }, [
    new RiceBugTaskImp('2-1', '查找login error 原因', Worker.LE, 3),
    new RiceBugTaskImp('2-2', '重啟login資料庫', Worker.ITSUPORT, 3),
  ]),

  // 第二回合
  new RiceBugProjectImp(2, '米ber 產品系統', true,
  { current: 3, last: 1 },
  { current: 10000, last: 10000 }, [
    new RiceBugTaskImp('3-1', '確認產品系統的規格', Worker.RO, 2),
    new RiceBugTaskImp('3-2', '審核相關成本', Worker.CFO, 2),
    new RiceBugTaskImp('3-3', '開發米 ber 產品系統', Worker.RD, 4),
    new RiceBugTaskImp('3-4', '建置米 ber 產品系統', Worker.CM, 3),
    new RiceBugTaskImp('3-5', '建置 米Ber 產品系統', Worker.LE, 4),
    new RiceBugTaskImp('3-6', '建置產品資料庫', Worker.ITSUPORT, 4),
    new RiceBugTaskImp('3-7', '配置產品資料表儲存空間', Worker.TO, 4),
  ]),
  new RiceBugProjectImp(2, '米ber RWD', true,
  { current: 3, last: 3 },
  { current: 5000, last: 5000 }, [
    new RiceBugTaskImp('4-1', '使系統支援RWD', Worker.RO, 3),
    new RiceBugTaskImp('4-2', '審核相關成本', Worker.CFO, 3),
    new RiceBugTaskImp('4-3', '開發米 ber RWD', Worker.RD, 4),
    new RiceBugTaskImp('4-4', '建置米 ber RWD', Worker.CM, 4),
    new RiceBugTaskImp('4-5', '使用 NODE 14 版環境', Worker.LE, 4),
    new RiceBugTaskImp('4-6', '升級資料庫Config V2', Worker.ITSUPORT, 4),
    new RiceBugTaskImp('4-7', '升級Server v2', Worker.TO, 4),
  ]),
  new RiceBugProjectImp(2, '蝦米購物 無法輸入免運', false,
  { current: -0.5, last:  -0.5 },
  { current: -1000, last: -1000 }, [
    new RiceBugTaskImp('5-1', '查找免運優惠錯誤問題,並通知IT Support重啟商品資料庫', Worker.LE, 2),
    new RiceBugTaskImp('5-2', '標題：重啟並還原商品資料庫', Worker.ITSUPORT, 4),
  ]),
  new RiceBugProjectImp(2, '蝦米購物 貨到付款', false,
  { current: -1, last:  -1 },
  { current: -2000, last: -2000 }, [
    new RiceBugTaskImp('6-1', '貨到付款系統故障,通知服務器重啟', Worker.LE, 2),
    new RiceBugTaskImp('6-2', '標題：重啟貨到付款資料庫', Worker.ITSUPORT, 4),
    new RiceBugTaskImp('6-3', '標題：重啟貨到付款服務器,並通知貨到付款資料庫重啟', Worker.TO, 4),
  ]),
  new RiceBugProjectImp(2, '蝦米購物 找不到歷史訂單', false,
  { current: -1, last:  -1 },
  { current: -2000, last: -2000 }, [
    new RiceBugTaskImp('7-1', '客戶訂單服務故障,資料庫無法連線', Worker.LE, 2),
    new RiceBugTaskImp('7-2', '訂單資料表連線失敗,請TO重啟訂單主機', Worker.ITSUPORT, 2),
    new RiceBugTaskImp('7-3', '標題：重啟訂單主機', Worker.TO, 2),
  ]),

  // 第三回合
  new RiceBugProjectImp(3, '米ber 信用卡', true,
  { current: 3, last:  1 },
  { current: 10000, last: 10000 }, [
    new RiceBugTaskImp('8-1', '確認信用卡功能規格及操作流程', Worker.RO, 3),
    new RiceBugTaskImp('8-2', '審核相關成本', Worker.CFO, 2),
    new RiceBugTaskImp('8-3', '開發米 ber 線上刷卡系統', Worker.RD, 5),
    new RiceBugTaskImp('8-4', '通知 IT Suport刷卡資料庫需更新', Worker.RD, 3),
    new RiceBugTaskImp('8-5', '通知 TO 刷卡server 需更新', Worker.RD, 3),
    new RiceBugTaskImp('8-6', '建置米 ber 線上刷卡系統', Worker.CM, 4),
    new RiceBugTaskImp('8-7', '準備線上刷卡交易憑證', Worker.LE, 4),
    new RiceBugTaskImp('8-8', '建立刷卡紀錄資料庫', Worker.ITSUPORT, 5),
    new RiceBugTaskImp('8-9', '設定刷卡Proxy，並升級Proxy 至V2', Worker.TO, 3),
  ]),
  new RiceBugProjectImp(3, '米ber 外送員後台', true,
  { current: 3, last: 3 },
  { current: 5000, last: 5000 }, [
    new RiceBugTaskImp('9-1', '確認後台目標對象以及核心功能', Worker.RO, 3),
    new RiceBugTaskImp('9-2', '審核相關成本', Worker.CFO, 3),
    new RiceBugTaskImp('9-3', '開發米 ber 外送員後台', Worker.RD, 4),
    new RiceBugTaskImp('9-4', '開發米 ber 外送員後台薪資派發系統', Worker.RD, 4),
    new RiceBugTaskImp('9-5', '開發米 ber 外送員後台', Worker.CM, 4),
    new RiceBugTaskImp('9-6', '開發米 ber 外送員後台薪資派發系統', Worker.CM, 4),
    new RiceBugTaskImp('9-7', '建立薪資派發執行環境', Worker.LE, 3),
    new RiceBugTaskImp('9-8', '建立薪資派發資料庫環境', Worker.ITSUPORT, 5),
    new RiceBugTaskImp('9-9', '設定薪資派發銀行連線通道', Worker.TO, 5),
  ]),
  new RiceBugProjectImp(3, '米ber GPS', true,
  { current: 3, last: 3 },
  { current: 10000, last: 10000 }, [
    new RiceBugTaskImp('10-1', '確認GPS的需求', Worker.RO, 3),
    new RiceBugTaskImp('10-2', '審核相關成本', Worker.CFO, 3),
    new RiceBugTaskImp('10-3', '開發米 ber GPS 定位功能', Worker.RD, 3),
    new RiceBugTaskImp('10-4', '開發米 ber 定位外送員追蹤功能', Worker.RD, 4),
    new RiceBugTaskImp('10-5', '開發米 ber GPS 定位功能', Worker.CM, 3),
    new RiceBugTaskImp('10-6', '開發米 ber 定位外送員追蹤功能', Worker.CM, 4),
    new RiceBugTaskImp('10-7', '設定ＧＰＳ連線通道,並記錄外送員所在位置', Worker.LE, 3),
    new RiceBugTaskImp('10-8', '建立外送員位置資料庫', Worker.ITSUPORT, 5),
    new RiceBugTaskImp('10-9', '連結全球ＧＰＳ系統', Worker.TO, 5),
  ]),
  new RiceBugProjectImp(3, '米ber APP', true,
  { current: 3, last: 3 },
  { current: 20000, last: 20000 }, [
    new RiceBugTaskImp('11-1', '參與使用者訪談', Worker.RO, 3),
    new RiceBugTaskImp('11-2', '審核相關成本', Worker.CFO, 3),
    new RiceBugTaskImp('11-3', '開發米 ber APP', Worker.RD, 5),
    new RiceBugTaskImp('11-4', '申請米 ber APP於數位平台上架', Worker.RD, 5),
    new RiceBugTaskImp('11-5', '開發米 ber APP', Worker.CM, 5),
    new RiceBugTaskImp('11-6', '申請米 ber APP於數位平台上架', Worker.CM, 5),
    new RiceBugTaskImp('11-7', '建置判斷連線裝置的服務,通知TO設定伺服器判斷', Worker.LE, 3),
    new RiceBugTaskImp('11-8', '建置欄位紀錄登入裝置', Worker.ITSUPORT, 5),
    new RiceBugTaskImp('11-9', '設定伺服器判斷連線進來的裝置', Worker.TO, 5),
  ]),
  new RiceBugProjectImp(3, '蝦米購物 直播', true,
  { current: 3, last: 3 },
  { current: 10000, last: 10000 }, [
    new RiceBugTaskImp('12-1', '確認直播功能的主要方向', Worker.RO, 3),
    new RiceBugTaskImp('12-2', '審核相關成本', Worker.CFO, 3),
    new RiceBugTaskImp('12-3', '開發蝦米購物直播功能 ', Worker.RD, 4),
    new RiceBugTaskImp('12-4', '協助 TO 直播 server 需更新', Worker.RD, 1),
    new RiceBugTaskImp('12-5', '協助 LE 使用 NODE 16 版環境', Worker.RD, 1),
    new RiceBugTaskImp('12-6', '開發蝦米購物直播功能 ', Worker.CM, 4),
    new RiceBugTaskImp('12-8', '協助 TO 直播 server 需更新', Worker.CM, 1),
    new RiceBugTaskImp('12-7', '協助 LE 使用 NODE 16 版環境', Worker.CM, 1),
    new RiceBugTaskImp('12-9', '使用 NODE 14 版環境', Worker.LE, 3),
    new RiceBugTaskImp('12-10', '建置直播資料庫', Worker.ITSUPORT, 5),
    new RiceBugTaskImp('12-11', '架設直播主機', Worker.TO, 5),
  ]),
  new RiceBugProjectImp(3, '蝦米購物 發票問題', false,
  { current: -1, last:  -1 },
  { current: -1500, last: -1500 }, [
    new RiceBugTaskImp('13-1', '擬定備案', Worker.RO, 2),
    new RiceBugTaskImp('13-2', '處理蝦米購物發票明細錯誤問題', Worker.RD, 2),
    new RiceBugTaskImp('13-3', '修正蝦米購物發票明細錯誤問題', Worker.CM, 2),
    new RiceBugTaskImp('13-4', '查找發票問題，通知TO查詢LOG', Worker.LE, 2),
    new RiceBugTaskImp('13-5', '還原發票系統資料庫', Worker.ITSUPORT, 4),
    new RiceBugTaskImp('13-6', '查詢發票系統log', Worker.TO, 4),
  ]),
  new RiceBugProjectImp(3, '蝦米購物 稅務系統位數不足', false,
  { current: 0, last:  0 },
  { current: -15000, last: -15000 }, [
    new RiceBugTaskImp('14-1', '與CFO確認 並通知技術協助處理', Worker.RO, 1),
    new RiceBugTaskImp('14-2', '通知技術協助處理', Worker.CFO, 1),
    new RiceBugTaskImp('14-3', '修改稅單金額位數', Worker.RD, 2),
    new RiceBugTaskImp('14-4', '修改稅單金額位數', Worker.CM, 2),
    new RiceBugTaskImp('14-5', '協助IT SUPPOER變更 稅務系統 資料庫欄位與盤點影響範圍', Worker.LE, 2),
    new RiceBugTaskImp('14-6', '變更稅務系統資料庫欄位', Worker.ITSUPORT, 5),
    new RiceBugTaskImp('14-7', '更新稅務系統主機並重新連結最新的資料庫', Worker.TO, 4),
  ]),
  new RiceBugProjectImp(3, '蝦米購物 商品上架頁跑版', false,
  { current: 0, last:  0 },
  { current: -1000, last: -1000 }, [
    new RiceBugTaskImp('15-1', '與設計確認畫面', Worker.RO, 1),
    new RiceBugTaskImp('15-2', '與RO確認處理優先權', Worker.CFO, 1),
    new RiceBugTaskImp('15-3', '修正蝦米購物跑版問題', Worker.RD, 1),
    new RiceBugTaskImp('15-4', '修正蝦米購物跑版問題', Worker.CM, 1),
    new RiceBugTaskImp('15-5', '通知更新蝦米購物商品系統', Worker.LE, 4),
    new RiceBugTaskImp('15-6', '蝦米購物商品系統上版作業', Worker.TO, 5),
    new RiceBugTaskImp('15-7', '清除蝦米購物商品系統主機CDN暫存', Worker.TO, 1),
  ]),

  // 第四回合
  new RiceBugProjectImp(4, '蝦米ber 評價系統', true,
  { current: 3, last:  -1 },
  { current: 20000, last: 20000 }, [
    new RiceBugTaskImp('16-1', '新增評價系統 確認相關規格與功能方向', Worker.RO, 3),
    new RiceBugTaskImp('16-2', '審核評價系統的製作成本', Worker.CFO, 3),
    new RiceBugTaskImp('16-3', '建置米 ber 評價系統', Worker.RD, 5),
    new RiceBugTaskImp('16-4', '變更評價系統ＡＰＩ連線位置', Worker.RD, 3),
    new RiceBugTaskImp('16-5', '建置米 ber 評價系統', Worker.CM, 5),
    new RiceBugTaskImp('16-6', '變更評價系統ＡＰＩ連線位置', Worker.CM, 3),
    new RiceBugTaskImp('16-7', '評價系統跨平台機制', Worker.LE, 3),
    new RiceBugTaskImp('16-8', '建立評價系統資料庫', Worker.ITSUPORT, 4),
    new RiceBugTaskImp('16-9', '評價即時更新主機建置', Worker.TO, 9),
  ]),
  new RiceBugProjectImp(4, '蝦米購物 無法登入', false,
  { current: -5, last:  -5 },
  { current: -15000, last: -15000 }, [
    new RiceBugTaskImp('17-1', '修復蝦米購物登入功能', Worker.RD, 5),
    new RiceBugTaskImp('17-2', '修復蝦米購物登入功能', Worker.CM, 5),
    new RiceBugTaskImp('17-3', '修正會員登入所需資料庫密碼欄位異常', Worker.ITSUPORT, 4),
    new RiceBugTaskImp('17-4', '修正會員登入所需資料庫地址欄位異常', Worker.ITSUPORT, 4),
    new RiceBugTaskImp('17-6', '修正會員登入連線主機異常', Worker.TO, 4),
    new RiceBugTaskImp('17-7', '重啟會員登入ＬＯＧ伺服器', Worker.TO, 4),
    new RiceBugTaskImp('17-8', '重裝會員登入在線推播主機', Worker.TO, 3),
  ]),
  new RiceBugProjectImp(4, '米蟲員工後台 bug', false,
  { current: 0, last:  0 },
  { current: 0, last: 0 }, [
    new RiceBugTaskImp('18-1', '制定發薪備案 並通知技術協助修復後台系統', Worker.CFO, 2),
    new RiceBugTaskImp('18-2', '修復米蟲員工後台薪資系統', Worker.RD, 4),
    new RiceBugTaskImp('18-3', '重設米蟲員工後台薪資設定', Worker.RD, 4),
    new RiceBugTaskImp('18-4', '修復米蟲員工後台薪資系統', Worker.CM, 4),
    new RiceBugTaskImp('18-5', '重設米蟲員工後台薪資設定', Worker.CM, 4),
    new RiceBugTaskImp('18-6', '查找薪資派發系統BUG', Worker.LE, 2),
    new RiceBugTaskImp('18-7', '修正薪資資料庫欄位型態錯誤', Worker.ITSUPORT, 5),
    new RiceBugTaskImp('18-8', '檢查所有薪資資料庫欄位正確性', Worker.ITSUPORT, 4),
    new RiceBugTaskImp('18-9', '重啟薪資服務主機', Worker.TO, 5),
    new RiceBugTaskImp('18-10', '套用薪資資料庫新的設定', Worker.TO, 4),
  ]),
];
export const trainingConfig  = new RiceBugProjectImp(2, '員工訓練', false,
  { current: 0, last: 0 },
  { current: 0, last: 0 }, [
    new RiceBugTaskImp('19-1', '對 IT Support 進行技術交流', Worker.RD, 2),
    new RiceBugTaskImp('19-2', '與 IT Support 進行技術交流', Worker.CM, 2),
    new RiceBugTaskImp('19-3', '進行技術交流訓練', Worker.LE, 4),
    new RiceBugTaskImp('19-4', '1. 與 AD 進行技術交流 2.對 TO 進行技術交流', Worker.ITSUPORT, 4),
    new RiceBugTaskImp('19-7', '與 IT support 進行技術交流', Worker.TO, 2),
  ]
  );
